<template>
   <div class="scene-02-container">
        <PolygonjsScene
            :loadFunction="loadFunction"
            @sceneready='onSceneReady'
            />
         <div class="controls disable-select">
             <input type="range" min="0.1" max="0.6" step="0.01" v-model="size"/>
         </div>
    </div>
</template>

<script lang="ts">
import Vue from 'vue';
import {PolygonjsScene} from '@polygonjs/vue2';
import {loadSceneAndMountAsync_scene_02} from '@/polygonjs/scenes/scene_02/autogenerated/loadSceneAndMountAsync';
import { PolySceneWithNodeMap_scene_02 } from '@/polygonjs/scenes/scene_02/autogenerated/PolySceneWithNodeMap';

export default Vue.extend({
  name: 'scene-02',
  components: {
    PolygonjsScene,
  },
  data: function(){
      return {
          size: 0.2,
          scene: null
      }
  },
  computed: {
    loadFunction: ()=>loadSceneAndMountAsync_scene_02,
  },
   watch: {
      size: function(){
          this.updateSize();
      }
  },
  methods: {
      onSceneReady: function(scene: PolySceneWithNodeMap_scene_02){
          this.$data.scene = scene;
          this.updateSize();
      },
      updateSize: function(){
          const scene = this.$data.scene as PolySceneWithNodeMap_scene_02|null
          if(!scene){return}
          scene.node('/rhino/fuse1').p.dist.set(this.$data.size)
      }
  }
});
</script>


<style scoped>
.scene-02-container {
    position: relative;
}
.controls {
    position: absolute;
    top: 0px;
    left: 0px;
    padding: 10px;
    width: 100%;
    pointer-events: none;
}
.controls input {
    pointer-events: auto;
    width: 95%;
}

.disable-select {
	user-select: none;
	-webkit-user-select: none;
	-khtml-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
}
</style>